server:
  port: 8090
spring:
  application-name: CLOUD-GATEWAY



  cloud:
    gateway:
      routes:
        - id: resturant-service
          uri: lb://resturant-service
          predicates:
            - Path=/resturant/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka