spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: 389869845201-utijrhrk8msrvtdn970502uoi86qhndl.apps.googleusercontent.com
            clientSecret: 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
 
  cloud:
    gateway:
      routes:
        - id: resturant-service
          uri: lb://resturant-service
          predicates:
            - Path=/resturant/** 
  application:
  name: CLOUD-GATEWAY


server:
  port: 6004