spring:
 cloud:
   gateway:
     routes:
       - id: resturant-service
         uri: lb://resturant-service
         predicates:
           - Path=/resturant/**

 application:
   name: CLOUD-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/