spring:
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          clone-on-start: true
          uri: https://github.com/junaid-repo/microservices-properties.git
  application:
    name: config-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888
